export const SignupType = {
    POST_SIGNUP_PENDING: "[SIGNUP][REQUEST] Try To Signup",
    POST_SIGNUP_FAILURE: "[SIGNUP][REQUEST] Signup Failed",
    POST_SIGNUP_SUCCESS: "[SIGNUP][REQUEST] Signup Successfull",
    lOGIN_LOGOUT: "lOGIN_LOGOUT",
    SIGNUPPAGE: "SignupPage",
    POST_REDIRECT_URL_PENDINGSUCCESS: "GET_URL_SUCCESS",
    POST_REDIRECT_URL_PENDING: "[URL][REQUEST] Try To URL",
  };
  