export const types = {
  POST_LOGIN_PENDING: "[LOGIN][REQUEST] Try To Login",
  POST_LOGIN_FAILURE: "[LOGIN][REQUEST] Login Failed",
  POST_LOGIN_SUCCESS: "[LOGIN][REQUEST] Login Successfull",
  lOGIN_LOGOUT: "lOGIN_LOGOUT",
  LOGINPAGE: "LoginPage",
  POST_REDIRECT_URL_PENDINGSUCCESS: "GET_URL_SUCCESS",
  POST_REDIRECT_URL_PENDING: "[URL][REQUEST] Try To URL",
};
